controller_manager:
  ros__parameters:
    update_rate: 300
    use_sim_time: true

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50
    action_monitor_rate: 20.0
